// <auto-generated />
namespace OnlineExam.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_database_or_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_database_or_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201812110408144_add_database_or_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
