// <auto-generated />
namespace OnlineExam.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class db_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201812091412026_db_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
