// <auto-generated />
namespace OnlineExam.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ans_modifyed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ans_modifyed));
        
        string IMigrationMetadata.Id
        {
            get { return "201812151905410_Ans_modifyed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
